### ISSUE TITLE
Source files are opened using default encoding - problems with cyrillics

### ISSUE THREAD

**Issue by ayaye** [mirmik/zenframe#1]
`update_text_field` in `zenframe/text_editor.py` uses default encoding to open a file.
It causes errors when utf-8 file contains cyrillic symbols.
I propose to specify encoding explicitly:

```
    def update_text_field(self):
        filetext = open(self.edited, encoding='utf-8').read()
        self.setPlainText(filetext)
```
In my case it works.

**Comment by mirmik** [comment]
Fixed.
https://github.com/mirmik/zenframe/commit/3b069f0497a74f1fe09b91e6be5f79cea62e8141
